Repository anime-team-pet-projects/trading-floor, pull requests merged in 2023-02, with the labels that each got.

#2 feat: TFB-01 | Добавлен flake8 в CI
  .github/workflows/test.yml
  src/apps/advertisement/admin.py
  src/apps/advertisement/models.py
  src/apps/advertisement/tests.py
  src/apps/advertisement/views.py
  src/apps/user/admin.py
  src/apps/user/models.py
  src/apps/user/tests.py
Labels: backend, feature

#3 feat: TFB | Добавлены объявления в панель администратора
  src/apps/advertisement/admin.py
Labels: backend, feature

#7 fix: TFB-03 | Изменение значения атрибута name в AdvertisementConfig
  src/apps/advertisement/apps.py
Labels: bug, backend

#8 fix: TFB | Исправлена версия python в poetry
  pyproject.toml
Labels: backend, fix
