Repository anime-team-pet-projects/trading-floor, pull requests merged in 2023-06, with the labels that each got.

#70 feat: TFB-28 | Добавлена возможность получения объявления по `id` автора
  src/api/v1/advertisement/filters.py
Labels: backend, feature

#68 fix: TFB-27 | Обновлено поле автора у объявлений
  src/api/v1/advertisement/serializers.py
Labels: backend, fix

#48 feat: TFB-16 | Добавлен функционал обновления пользователя, изменена логика аватарки
  poetry.lock
  pyproject.toml
  src/api/common/auth/serializers.py
  src/api/common/auth/tests/test_view/test_authorization_google.py
  src/api/v1/advertisement/serializers.py
  src/api/v1/user/serializers.py
  src/api/v1/user/tests/test_view/test_detail_user_view.py
  src/api/v1/user/tests/test_view/test_me_view.py
  src/api/v1/user/views.py
  src/apps/advertisement/migrations/0001_initial.py
  src/apps/advertisement/migrations/0002_initial.py
  src/apps/advertisement/migrations/0003_advertisement_created_at.py
  src/apps/advertisement/models.py
  src/apps/user/migrations/0001_initial.py
  src/apps/user/models.py
  src/config/settings.py
  src/utils/colors.py
  src/utils/mixins/views.py
Labels: backend, feature

#69 fix: TFB-26 | Images приходят в правильном формате
  src/api/v1/advertisement/serializers.py
Labels: backend, fix

#60 feat: TFB-04 | Свёрстана главная страница
  .gitignore
  components.d.ts
  index.html
  src/api/KY/AdvertisementService/advertisement.api.ts
  src/api/KY/AdvertisementService/advertisement.types.ts
  src/api/KY/AuthService/auth.api.ts
  src/api/KY/AuthService/auth.types.ts
  src/api/KY/TokenService/token.api.ts
  src/api/KY/UserService/user.api.ts
  src/assets/icons/notification.svg
  src/assets/icons/profile.svg
  src/assets/icons/vki.svg
  src/assets/images/background.png
  src/components/Forms/CreateAdvertisementForm.vue
  src/components/Forms/GoogleRegistrationForm.vue
  src/components/widgets/AdvertisementList.vue
  src/components/widgets/AdvertisementPreview/AdvertisementPreview.types.ts
  src/components/widgets/AdvertisementPreview/AdvertisementPreview.vue
  src/components/widgets/CategoriesSidebar.vue
  src/components/widgets/GoogleAuth.vue
  src/components/widgets/TheFooter.vue
  src/components/widgets/TheHeader.vue
  src/components/widgets/buttons/AdvertisementType.vue
  src/components/widgets/buttons/NewAdvertisement.vue
  src/components/widgets/buttons/ProfileIcon.vue
  src/components/widgets/buttons/TheNotification.vue
  src/layouts/AuthorizationLayout.vue
  src/layouts/DefaultLayout.vue
  src/main.ts
  src/pages/HomePage.vue
  src/pages/LoginPage.vue
  src/router/index.ts
  src/styles/resources/mixins/_fonts.scss
  src/styles/resources/mixins/_grid.scss
  src/styles/resources/variables/_colors.scss
  src/styles/resources/variables/_sizes.scss
  src/styles/vendor/el-plus/_input.scss
  src/types/advertisementTypes.ts
  src/types/authFormTypes.ts
  src/types/formTypes.ts
  src/types/userTypes.ts
Labels: feature, frontend

#76 feat: TFB-31 | Тест на фильтрацию по открытым и закрытым объявлениям
  src/api/v1/advertisement/filters.py
  src/api/v1/advertisement/serializers.py
  src/api/v1/advertisement/tests/test_view/test_advertisement_filters.py
  src/api/v1/user/serializers.py
  src/factories.py
Labels: backend, feature
