Repository anime-team-pet-projects/trading-floor, pull requests merged in 2023-04, with the labels that each got.

#31 feat: TFB-08 | Добавлен новый swagger
  poetry.lock
  pyproject.toml
  src/api/urls.py
  src/api/v1/urls.py
  src/config/settings.py
  src/config/urls.py
Labels: backend, feature

#32 feat: TFB-12 | Добавлен permission на авторизированного и активированного пользователя
  src/apps/user/permissions.py
Labels: backend, feature

#26 TFF-01, TFF-02: Регистрация, авторизация, включая Google OAuth
  .env.dist
  .eslintrc.cjs
  .prettierrc.json
  components.d.ts
  cypress.config.ts
  cypress/e2e/example.cy.ts
  cypress/support/commands.ts
  cypress/support/component.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
  src/App.vue
  src/api/AxiosService/axiosService.ts
  src/api/AxiosService/axiosService.types.ts
  src/api/auth/auth.api.ts
  src/api/auth/auth.types.ts
  src/api/user/user.api.ts
  src/api/user/user.types.ts
  src/components/Forms/LoginFormPage.vue
  src/components/Forms/RegistrationFormPage.vue
  src/components/LoginForm.vue
  src/components/RegistrationForm.vue
  src/components/common/CInput/CInput.type.ts
  src/components/common/CInput/CInput.vue
  src/components/common/CInput/__tests__/CInput.test.ts
  src/components/common/IconTemplate.vue
  src/components/widgets/GoogleAuth.vue
  src/constants/formRules.ts
  src/constants/routeNames.ts
  src/layouts/AuthLayout.vue
  src/layouts/AuthorizationLayout.vue
  src/main.ts
  src/pages/AuthPage.vue
  src/pages/HomePage.vue
  src/presets/messages.ts
  src/router/index.ts
  src/stores/authStore.ts
  src/styles/base.scss
  src/types/auth.ts
  src/types/authFormTypes.ts
  src/validators/auth.ts
  src/validators/common.ts
  stylelint.config.js
  vite.config.ts
Labels: feature, frontend

#34 fix: TFF-02, TFF-01
  components.d.ts
  src/components/Forms/LoginForm.vue
  src/components/Forms/RegistrationForm.vue
  src/pages/LoginPage.vue
  src/pages/RegistrationPage.vue
  src/router/index.ts
Labels: fix, frontend

#39 feat: TFB-14 | Добавлены тесты в CI/CD. Скомпенсированы миграции
  .github/workflows/lint.yml
  .github/workflows/test.yml
  docker-compose.yaml
  src/api/common/auth/tests/test_view/test_authorization_google.py
  src/apps/advertisement/migrations/0001_initial.py
  src/apps/advertisement/migrations/0002_alter_advertisementcategory_title.py
  src/apps/advertisement/migrations/0002_initial.py
  src/apps/user/migrations/0001_initial.py
  src/apps/user/migrations/0003_user_is_register_alter_user_is_active.py
Labels: backend, tests
