Repository anime-team-pet-projects/trading-floor, pull requests merged in 2023-03, with the labels that each got.

#10 feat: TFB-01 | Добавлена регистрация и авторизация для пользователей
  .dockerignore
  poetry.lock
  pyproject.toml
  src/api/common/auth/urls.py
  src/api/urls.py
  src/api/v1/user/serializers.py
  src/api/v1/user/urls.py
  src/api/v1/user/views.py
  src/apps/advertisement/models.py
  src/apps/user/admin.py
  src/apps/user/models.py
  src/config/settings.py
  src/config/urls.py
  src/utils/strings.py
Labels: backend, feature

#16 feat: TFB-04 | Добавлены тесты и исправлен нужный функционал
  poetry.lock
  pyproject.toml
  pytest.ini
  src/api/v1/user/serializers.py
  src/api/v1/user/tests/test_view/__init__.py
  src/api/v1/user/tests/test_view/test_detail_user_view.py
  src/api/v1/user/tests/test_view/test_me_view.py
  src/api/v1/user/tests/test_view/test_register_view.py
  src/api/v1/user/urls.py
  src/api/v1/user/views.py
  src/conftest.py
  src/factories.py
  src/utils/tests/__init__.py
  src/utils/tests/tests_strings.py
Labels: backend, feature, tests

#18 feat: TFB-05 | Добавлено описание ошибок ко всем тестам
  src/api/v1/user/tests/test_view/test_detail_user_view.py
  src/api/v1/user/tests/test_view/test_me_view.py
  src/api/v1/user/tests/test_view/test_register_view.py
Labels: backend, feature, tests

#19 feat: TFB-04 | Подключен swagger
  poetry.lock
  pyproject.toml
  src/config/settings.py
  src/config/urls.py
Labels: backend, feature

#22 fix: TFB-07 | Удален `api/` из auth URL
  src/api/common/auth/urls.py
Labels: backend, fix

#29 feat: TFB-09 | Добавлена авторизация/регистрация с помощью Google OAuth2
  .env.example
  .flake8
  .gitignore
  poetry.lock
  pyproject.toml
  src/api/common/auth/serializers.py
  src/api/common/auth/tests/__init__.py
  src/api/common/auth/tests/test_view/__init__.py
  src/api/common/auth/tests/test_view/test_authorization_google.py
  src/api/common/auth/urls.py
  src/api/common/auth/views.py
  src/api/v1/user/tests/test_view/test_detail_user_view.py
  src/api/v1/user/tests/test_view/test_me_view.py
  src/api/v1/user/tests/test_view/test_register_view.py
  src/api/v1/user/urls.py
  src/api/v1/user/views.py
  src/apps/user/migrations/0002_alter_user_is_active_alter_user_room_number.py
  src/apps/user/models.py
  src/config/settings.py
  src/conftest.py
  src/library/oauth/__init__.py
  src/library/oauth/google.py
  src/library/oauth/models.py
Labels: backend, feature
