Repository anime-team-pet-projects/trading-floor, pull requests merged in 2023-05, with the labels that each got.

#46 ref: TFB-15 | Изменено название serializer'а
  src/api/v1/advertisement/serializers.py
  src/api/v1/advertisement/views.py
Labels: backend, refactor

#54 fix: TFB-22 | Добавлено поле `id` в serializers
  .github/workflows/test.yml
  .gitignore
  src/api/v1/advertisement/serializers.py
Labels: backend, fix

#56 fix: TFB-21 | Исправлено API для категорий
  src/api/v1/advertisement/tests/test_view/test_advertisement_categories.py
  src/api/v1/advertisement/urls.py
  src/api/v1/advertisement/views.py
Labels: backend, fix

#61 feat: TFB-24 | Добавлена дата создания в `Advertisement`
  src/api/v1/advertisement/serializers.py
  src/apps/advertisement/migrations/0003_advertisement_created_at.py
  src/apps/advertisement/models.py
Labels: backend, feature
